k8s_yaml([
    './infra/k8s/auth-depl.yaml',
    './infra/k8s/auth-mongo-depl.yaml',
    './infra/k8s/ingress-srv.yaml',
])

docker_build('jaimuepe/auth', './auth', live_update=[
   sync('./auth/src', '/app/src')
])